export interface BrazilianState {
  abbr: string;
  name: string;
}

export const STATES: BrazilianState[] = [
  { abbr: "AC", name: "Acre" },
  { abbr: "AL", name: "Alagoas" },
  { abbr: "AP", name: "Amapá" },
  { abbr: "AM", name: "Amazonas" },
  { abbr: "BA", name: "Bahia" },
  { abbr: "CE", name: "Ceará" },
  { abbr: "DF", name: "Distrito Federal" },
  { abbr: "ES", name: "Espírito Santo" },
  { abbr: "GO", name: "Goiás" },
  { abbr: "MA", name: "Maranhão" },
  { abbr: "MT", name: "Mato Grosso" },
  { abbr: "MS", name: "Mato Grosso do Sul" },
  { abbr: "MG", name: "Minas Gerais" },
  { abbr: "PA", name: "Pará" },
  { abbr: "PB", name: "Paraíba" },
  { abbr: "PR", name: "Paraná" },
  { abbr: "PE", name: "Pernambuco" },
  { abbr: "PI", name: "Piauí" },
  { abbr: "RJ", name: "Rio de Janeiro" },
  { abbr: "RN", name: "Rio Grande do Norte" },
  { abbr: "RS", name: "Rio Grande do Sul" },
  { abbr: "RO", name: "Rondônia" },
  { abbr: "RR", name: "Roraima" },
  { abbr: "SC", name: "Santa Catarina" },
  { abbr: "SP", name: "São Paulo" },
  { abbr: "SE", name: "Sergipe" },
  { abbr: "TO", name: "Tocantins" },
];

export const CITIES_BY_STATE: Record<string, string[]> = {
  AC: [
    "Rio Branco",
    "Cruzeiro do Sul",
    "Sena Madureira",
    "Tarauacá",
    "Feijó",
    "Brasileia",
    "Epitaciolândia",
    "Mâncio Lima",
    "Rodrigues Alves",
    "Acrelândia",
    "Plácido de Castro",
    "Xapuri",
    "Jordão",
    "Manoel Urbano",
  ],
  AL: [
    "Maceió",
    "Arapiraca",
    "Palmeira dos Índios",
    "Rio Largo",
    "Penedo",
    "União dos Palmares",
    "São Miguel dos Campos",
    "Coruripe",
    "Santana do Ipanema",
    "Delmiro Gouveia",
    "Campo Alegre",
    "Murici",
    "Marechal Deodoro",
    "Pilar",
    "Joaquim Gomes",
    "Viçosa",
    "Atalaia",
    "São Luís do Quitunde",
  ],
  AP: [
    "Macapá",
    "Santana",
    "Laranjal do Jari",
    "Oiapoque",
    "Mazagão",
    "Porto Grande",
    "Pedra Branca do Amapari",
    "Serra do Navio",
    "Tartarugalzinho",
    "Amapá",
  ],
  AM: [
    "Manaus",
    "Parintins",
    "Itacoatiara",
    "Manacapuru",
    "Coari",
    "Tefé",
    "Tabatinga",
    "Maués",
    "Humaitá",
    "Manicoré",
    "Benjamin Constant",
    "Borba",
    "Nova Olinda do Norte",
    "Presidente Figueiredo",
    "Rio Preto da Eva",
    "Careiro",
    "Iranduba",
    "Lábrea",
    "Autazes",
    "Fonte Boa",
  ],
  BA: [
    "Salvador",
    "Feira de Santana",
    "Vitória da Conquista",
    "Camaçari",
    "Itabuna",
    "Juazeiro",
    "Lauro de Freitas",
    "Ilhéus",
    "Jequié",
    "Teixeira de Freitas",
    "Barreiras",
    "Porto Seguro",
    "Simões Filho",
    "Paulo Afonso",
    "Eunápolis",
    "Alagoinhas",
    "Serrinha",
    "Santo Antônio de Jesus",
    "Cruz das Almas",
    "Valença",
    "Senhor do Bonfim",
    "Jacobina",
    "Guanambi",
    "Brumado",
    "Canavieiras",
    "Itapetinga",
    "Luís Eduardo Magalhães",
    "Caetité",
    "Ibotirama",
    "Irecê",
  ],
  CE: [
    "Fortaleza",
    "Caucaia",
    "Juazeiro do Norte",
    "Maracanaú",
    "Sobral",
    "Crato",
    "Itapipoca",
    "Maranguape",
    "Iguatu",
    "Quixadá",
    "Pacatuba",
    "Russas",
    "Aquiraz",
    "Canindé",
    "Crateús",
    "Limoeiro do Norte",
    "Tianguá",
    "Cascavel",
    "Aracati",
    "Horizonte",
    "Eusébio",
    "Icó",
    "Quixeramobim",
    "Camocim",
    "Barbalha",
    "Morada Nova",
    "São Gonçalo do Amarante",
  ],
  DF: [
    "Brasília",
    "Ceilândia",
    "Taguatinga",
    "Samambaia",
    "Plano Piloto",
    "Gama",
    "Águas Claras",
    "Guará",
    "Sobradinho",
    "Planaltina",
    "Recanto das Emas",
    "Santa Maria",
    "São Sebastião",
    "Brazlândia",
    "Paranoá",
    "Riacho Fundo",
    "Núcleo Bandeirante",
    "Lago Sul",
    "Lago Norte",
    "Cruzeiro",
    "Park Way",
  ],
  ES: [
    "Vitória",
    "Serra",
    "Vila Velha",
    "Cariacica",
    "Cachoeiro de Itapemirim",
    "Linhares",
    "Colatina",
    "Guarapari",
    "São Mateus",
    "Aracruz",
    "Viana",
    "Nova Venécia",
    "Barra de São Francisco",
    "Itapemirim",
    "Marataízes",
    "Afonso Cláudio",
    "Domingos Martins",
    "Presidente Kennedy",
    "Conceição da Barra",
    "João Neiva",
  ],
  GO: [
    "Goiânia",
    "Aparecida de Goiânia",
    "Anápolis",
    "Rio Verde",
    "Luziânia",
    "Águas Lindas de Goiás",
    "Valparaíso de Goiás",
    "Trindade",
    "Formosa",
    "Novo Gama",
    "Itumbiara",
    "Senador Canedo",
    "Catalão",
    "Jataí",
    "Planaltina",
    "Caldas Novas",
    "Goianésia",
    "Inhumas",
    "Mineiros",
    "Morrinhos",
    "Goiás",
    "Cristalina",
    "Uruaçu",
    "Jaraguá",
    "Pirenópolis",
    "Santa Helena de Goiás",
  ],
  MA: [
    "São Luís",
    "Imperatriz",
    "São José de Ribamar",
    "Timon",
    "Caxias",
    "Codó",
    "Açailândia",
    "Bacabal",
    "Balsas",
    "Santa Inês",
    "Pinheiro",
    "Chapadinha",
    "Barreirinhas",
    "Paço do Lumiar",
    "Coroatá",
    "Zé Doca",
    "Pedreiras",
    "Viana",
    "Itapecuru Mirim",
    "São João dos Patos",
  ],
  MT: [
    "Cuiabá",
    "Várzea Grande",
    "Rondonópolis",
    "Sinop",
    "Tangará da Serra",
    "Cáceres",
    "Sorriso",
    "Lucas do Rio Verde",
    "Primavera do Leste",
    "Barra do Garças",
    "Alta Floresta",
    "Peixoto de Azevedo",
    "Colíder",
    "Nova Mutum",
    "Juara",
    "Pontes e Lacerda",
    "Juína",
    "Guarantã do Norte",
    "Campo Verde",
    "Nova Xavantina",
  ],
  MS: [
    "Campo Grande",
    "Dourados",
    "Três Lagoas",
    "Corumbá",
    "Ponta Porã",
    "Naviraí",
    "Nova Andradina",
    "Aquidauana",
    "Sidrolândia",
    "Paranaíba",
    "Maracaju",
    "Rio Brilhante",
    "Coxim",
    "Amambai",
    "Bonito",
    "Ivinhema",
    "Jardim",
    "Miranda",
    "Anastácio",
    "Iguatemi",
  ],
  MG: [
    "Belo Horizonte",
    "Uberlândia",
    "Contagem",
    "Juiz de Fora",
    "Betim",
    "Montes Claros",
    "Ribeirão das Neves",
    "Uberaba",
    "Governador Valadares",
    "Ipatinga",
    "Sete Lagoas",
    "Divinópolis",
    "Santa Luzia",
    "Ibirité",
    "Poços de Caldas",
    "Patos de Minas",
    "Pouso Alegre",
    "Teófilo Otoni",
    "Barbacena",
    "Sabará",
    "Varginha",
    "Conselheiro Lafaiete",
    "Muriaé",
    "Araguari",
    "Ituiutaba",
    "Coronel Fabriciano",
    "Timóteo",
    "Ubá",
    "Lavras",
    "Itajubá",
    "Passos",
    "Araxá",
    "João Monlevade",
    "Itaúna",
    "Formiga",
    "Curvelo",
    "Viçosa",
    "Caratinga",
    "Manhuaçu",
    "Pará de Minas",
  ],
  PA: [
    "Belém",
    "Ananindeua",
    "Santarém",
    "Marabá",
    "Castanhal",
    "Parauapebas",
    "Altamira",
    "Itaituba",
    "Abaetetuba",
    "Cametá",
    "Tucuruí",
    "Barcarena",
    "Tailândia",
    "Paragominas",
    "Marituba",
    "Redenção",
    "Benevides",
    "Bragança",
    "Capanema",
    "Vigia",
    "Breves",
    "Oriximiná",
    "Óbidos",
    "Conceição do Araguaia",
  ],
  PB: [
    "João Pessoa",
    "Campina Grande",
    "Santa Rita",
    "Patos",
    "Bayeux",
    "Sousa",
    "Cajazeiras",
    "Guarabira",
    "Cabedelo",
    "Sapé",
    "Esperança",
    "Mamanguape",
    "Queimadas",
    "Monteiro",
    "Lagoa Seca",
    "Itabaiana",
    "Pombal",
    "Princesa Isabel",
    "Lucena",
    "Areia",
  ],
  PR: [
    "Curitiba",
    "Londrina",
    "Maringá",
    "Ponta Grossa",
    "Cascavel",
    "São José dos Pinhais",
    "Foz do Iguaçu",
    "Colombo",
    "Guarapuava",
    "Paranaguá",
    "Araucária",
    "Toledo",
    "Apucarana",
    "Pinhais",
    "Campo Largo",
    "Almirante Tamandaré",
    "Umuarama",
    "Piraquara",
    "Cambé",
    "Sarandi",
    "Fazenda Rio Grande",
    "Paranavaí",
    "Francisco Beltrão",
    "Cianorte",
    "Palmas",
    "Telêmaco Borba",
    "Castro",
    "Arapongas",
    "Rolândia",
    "Irati",
    "Medianeira",
    "Cornélio Procópio",
    "Pato Branco",
    "União da Vitória",
    "Ibiporã",
    "Bandeirantes",
  ],
  PE: [
    "Recife",
    "Caruaru",
    "Olinda",
    "Petrolina",
    "Paulista",
    "Jaboatão dos Guararapes",
    "Cabo de Santo Agostinho",
    "Camaragibe",
    "Garanhuns",
    "Vitória de Santo Antão",
    "Igarassu",
    "Abreu e Lima",
    "Santa Cruz do Capibaribe",
    "Araripina",
    "Salgueiro",
    "Goiana",
    "Carpina",
    "Gravatá",
    "Arcoverde",
    "Serra Talhada",
    "Caruaru",
    "Bezerros",
    "Surubim",
    "Limoeiro",
    "São Lourenço da Mata",
  ],
  PI: [
    "Teresina",
    "Parnaíba",
    "Picos",
    "Piripiri",
    "Floriano",
    "Campo Maior",
    "Barras",
    "Esperantina",
    "Oeiras",
    "Corrente",
    "Pedro II",
    "União",
    "José de Freitas",
    "Altos",
    "São Raimundo Nonato",
    "Valença do Piauí",
    "Batalha",
    "Uruçuí",
  ],
  RJ: [
    "Rio de Janeiro",
    "São Gonçalo",
    "Duque de Caxias",
    "Nova Iguaçu",
    "Niterói",
    "Belford Roxo",
    "São João de Meriti",
    "Campos dos Goytacazes",
    "Petrópolis",
    "Volta Redonda",
    "Macaé",
    "Itaboraí",
    "Magé",
    "Mesquita",
    "Queimados",
    "Nilópolis",
    "Angra dos Reis",
    "Resende",
    "Maricá",
    "Cabo Frio",
    "Barra Mansa",
    "Nova Friburgo",
    "Teresópolis",
    "Três Rios",
    "Itaperuna",
    "Rio das Ostras",
    "Araruama",
    "São Pedro da Aldeia",
    "Guapimirim",
    "Paracambi",
    "Itaguaí",
    "Japeri",
    "Seropédica",
  ],
  RN: [
    "Natal",
    "Mossoró",
    "Parnamirim",
    "Caicó",
    "Assu",
    "Currais Novos",
    "Santa Cruz",
    "Macaíba",
    "Ceará-Mirim",
    "Apodi",
    "João Câmara",
    "Nova Cruz",
    "São José de Mipibu",
    "Touros",
    "Pau dos Ferros",
    "Extremoz",
    "Nísia Floresta",
  ],
  RS: [
    "Porto Alegre",
    "Caxias do Sul",
    "Canoas",
    "Pelotas",
    "Santa Maria",
    "Gravataí",
    "Viamão",
    "Novo Hamburgo",
    "São Leopoldo",
    "Rio Grande",
    "Alvorada",
    "Passo Fundo",
    "Sapucaia do Sul",
    "Uruguaiana",
    "Santa Cruz do Sul",
    "Cachoeirinha",
    "Bagé",
    "Bento Gonçalves",
    "Erechim",
    "Guaíba",
    "Cachoeira do Sul",
    "Lajeado",
    "Sapiranga",
    "Montenegro",
    "Alegrete",
    "Farroupilha",
    "Venâncio Aires",
    "Ijuí",
    "Vacaria",
    "Três de Maio",
    "São Gabriel",
    "Cruz Alta",
    "Frederico Westphalen",
    "Carazinho",
    "Santana do Livramento",
    "Osório",
    "Torres",
    "Tramandaí",
  ],
  RO: [
    "Porto Velho",
    "Ji-Paraná",
    "Ariquemes",
    "Vilhena",
    "Cacoal",
    "Rolim de Moura",
    "Guajará-Mirim",
    "Jaru",
    "Ouro Preto do Oeste",
    "Espigão do Oeste",
    "Pimenta Bueno",
    "Presidente Médici",
    "Colorado do Oeste",
    "Alta Floresta do Oeste",
  ],
  RR: [
    "Boa Vista",
    "Rorainópolis",
    "Caracaraí",
    "Alto Alegre",
    "Mucajaí",
    "Cantá",
    "Pacaraima",
    "Bonfim",
    "Amajari",
  ],
  SC: [
    "Florianópolis",
    "Joinville",
    "Blumenau",
    "São José",
    "Chapecó",
    "Criciúma",
    "Jaraguá do Sul",
    "Lages",
    "Itajaí",
    "Palhoça",
    "Balneário Camboriú",
    "São Miguel do Oeste",
    "Brusque",
    "Tubarão",
    "Concórdia",
    "Caçador",
    "Mafra",
    "Araranguá",
    "Navegantes",
    "Camboriú",
    "São Bento do Sul",
    "Içara",
    "Gaspar",
    "Rio do Sul",
    "Videira",
    "Indaial",
    "Canoinhas",
    "Xanxerê",
    "Joaçaba",
    "São Francisco do Sul",
    "Laguna",
    "Imbituba",
    "Tijucas",
    "Porto União",
    "Herval do Oeste",
  ],
  SP: [
    "São Paulo",
    "Guarulhos",
    "Campinas",
    "São Bernardo do Campo",
    "Santo André",
    "São José dos Campos",
    "Osasco",
    "Ribeirão Preto",
    "Sorocaba",
    "Mauá",
    "Santos",
    "Diadema",
    "Jundiaí",
    "Piracicaba",
    "Bauru",
    "São José do Rio Preto",
    "Franca",
    "Guarujá",
    "Taubaté",
    "Limeira",
    "Suzano",
    "Barueri",
    "Taboão da Serra",
    "Sumaré",
    "São Carlos",
    "Praia Grande",
    "Americana",
    "Cotia",
    "Araraquara",
    "Marília",
    "Araçatuba",
    "Presidente Prudente",
    "Itaquaquecetuba",
    "Jacareí",
    "Botucatu",
    "Rio Claro",
    "Hortolândia",
    "Indaiatuba",
    "Carapicuíba",
    "Salto",
    "São Caetano do Sul",
    "Catanduva",
    "Ourinhos",
    "Registro",
    "Cubatão",
    "Embu das Artes",
    "Itapevi",
    "Ferraz de Vasconcelos",
    "Caçapava",
    "Mogi Guaçu",
    "Valinhos",
    "Vinhedo",
    "Itu",
    "Atibaia",
    "Bragança Paulista",
    "Caraguatatuba",
    "Ubatuba",
    "São Sebastião",
    "Ilhabela",
    "Itanhaém",
    "Mongaguá",
    "Peruíbe",
    "Votuporanga",
    "São Joaquim da Barra",
    "Lins",
    "Birigui",
    "Andradina",
    "Assis",
    "Tupã",
    "Presidente Epitácio",
    "Dracena",
    "Rancharia",
    "Avaré",
    "Itapetininga",
    "Tatuí",
    "Boituva",
    "Porto Feliz",
    "Amparo",
    "Mogi Mirim",
    "Casa Branca",
    "Itatiba",
    "Louveira",
    "Campo Limpo Paulista",
    "Cabreúva",
    "Pirapora do Bom Jesus",
    "Santana de Parnaíba",
    "Barueri",
  ],
  SE: [
    "Aracaju",
    "Nossa Senhora do Socorro",
    "Lagarto",
    "Itabaiana",
    "São Cristóvão",
    "Estância",
    "Tobias Barreto",
    "Simão Dias",
    "Barra dos Coqueiros",
    "Carmópolis",
    "Propriá",
    "Itabaianinha",
    "Poço Redondo",
    "Canindé de São Francisco",
  ],
  TO: [
    "Palmas",
    "Araguaína",
    "Gurupi",
    "Porto Nacional",
    "Paraíso do Tocantins",
    "Guaraí",
    "Tocantinópolis",
    "Miracema do Tocantins",
    "Pedro Afonso",
    "Colinas do Tocantins",
    "Formoso do Araguaia",
    "Dianópolis",
    "Arraias",
    "Taguatinga",
    "Natividade",
  ],
};
